import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/elements/Footer";
import Link from "next/link";
import Navbar from "@/components/elements/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="bg-slate-100 dark:bg-[#243041] min-h-dvh w-screen flex flex-col justify-between">
            <div className="w-full h-full flex flex-col items-center">
              <Navbar />

              <div className="w-full max-w-[1584px]">
                <section className="w-full flex flex-col justify-center mt-8 px-4">
                  <p className="text-center text-3xl font-bold max-w-[80%] mx-auto">
                    Built to empower your{" "}
                    <span className="bg-gradient-to-r from-slate-500 from-30% to-slate-200 dark:to-[#2D3848] to-90% bg-clip-text text-transparent">
                      workflow.
                    </span>
                  </p>
                  <p className="text-center mt-1 font-semibold text-neutral-700 dark:text-zinc-300">
                    Discover ready-to-use components instantly. Customize, copy,
                    and craft-your way!
                  </p>

                  <div className="w-full flex justify-center mt-6">
                    <Link
                      href={"/docs/button"}
                      className="bg-slate-500 py-2 px-4 transition-all rounded-lg hover:rounded-[50px] ease-in-out duration-500 text-sm text-white hover:bg-slate-600"
                    >
                      Browse Components
                    </Link>
                  </div>
                </section>

                {children}
              </div>
            </div>

            <Footer />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
